### ISSUE TITLE
Show recently added sets and pins

### ISSUE THREAD

**Issue by scytherswings** [PinsterTeam/PinsterApi#20]
we should support a query that allows users to get recently aded sets ad pins mixed together. Maybe a UNION or something?

**Comment by scytherswings** [comment]
This should be the default result used by the UI I would think. Otherwise the archive's front page will never change once pins are added. @stretch1414 ^^^

I'm thinking the endpoint might be something like GET `/search?subject[]=pins&subject[]=assortments&order=recently_added` *the `[]` should be urlencoded to make sure we are compliant with some RFC out there, I think it's `%5b` and `%5d` or something like that.

**Comment by stretch1414** [comment]
Makes sense to me.  Would be good if the user had a different experience every time.

**Comment by scytherswings** [comment]
One caveat goes back to our discussion in the meeting talking about opening up sets vs pins in the search results. I think we solved that with #28 though so it *should* work ok in the UI/UX we have?

**Comment by scytherswings** [comment]
Scratch the part about including `assortments`/`sets` in search results, we talked about how to handle this with #28 and metadata stuff
